### ISSUE TITLE
Please increase font size for paragraphs

### ISSUE THREAD

**Issue by elmasse** [hypercore-protocol/blog#1]
Hey Guys!

Awesome work launching yesterday!!! One thing I would like to ask is to increase the font size for both Blog and Site, 14px is quite annoying and it gets really hard to read. For blog posts the only way I can pass the first paragraph is using the Safari Reader (which by default makes it 18px,  some sort of sweet spot IMO).

Just that, feel free to close the issue if you consider the current font is more than adequate.

Thanks in advance!
Max

**Comment by andrewosh** [comment]
Thanks Max, we debated the font size and perhaps chose wrong :)

I'll bump it up to 16.
